[server]
follow_symlink = false
browser = "default"

[completion]
activate_on_typing = true
copilot = "github"

[display]
default_table_page_size = 10
default_width = "medium"
code_editor_font_size = 16
default_table_max_columns = 50
dataframes = "rich"
cell_output = "above"
reference_highlighting = false
theme = "light"

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[experimental]

[package_management]
manager = "uv"

[language_servers.ty]
enabled = false

[language_servers.basedpyright]

[language_servers.pylsp]
enable_flake8 = false
enable_pylint = false
enable_mypy = true
enable_ruff = true
enabled = true
enable_pyflakes = false
enable_pydocstyle = false

[snippets]
custom_paths = []
include_default_snippets = true

[runtime]
auto_reload = "off"
std_stream_max_bytes = 1000000
default_auto_download = []
watcher_on_save = "lazy"
on_cell_change = "autorun"
reactive_tests = true
auto_instantiate = false
default_sql_output = "auto"
output_max_bytes = 8000000

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = true

[mcp]
presets = []

[mcp.mcpServers]

[formatting]
line_length = 100

[diagnostics]
sql_linter = true

[ai]
inline_tooltip = false
mode = "manual"
rules = ""

[ai.models]
displayed_models = []
custom_models = []
