import marimo

__generated_with = "0.12.5"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    return (mo,)


@app.cell
def _():
    import re
    return (re,)


@app.cell
def _():
    def my_decorator(func):
        def wrapper():
            print("Something is happening before the function is called.")
            func()
            print("Something is happening after the function is called.")
        return wrapper

    @my_decorator
    def say_hello():
        print("Hello!")

    say_hello()
    return my_decorator, say_hello


@app.cell
def MyClass():
    class MyClass:
        class_variable = "I am a class variable"

        @classmethod
        def class_method(cls):
            print(f"Accessing class variable: {cls.class_variable}")

        @staticmethod
        def static_method():
            print("I am a static method. I don't need class or instance data.")
    return (MyClass,)


@app.cell
def _(MyClass):
    MyClass.class_method()
    return


@app.cell
def _(MyClass):
    MyClass.static_method()
    return


@app.cell
def _(re):
    class Sequence:
        def __init__(self, sequence):
            self.sequence = sequence.upper()

        def get_length(self):
            """Returns the length of the sequence."""
            return len(self.sequence)

        def get_composition(self):
            """Returns the composition of each character in the sequence."""
            composition = {}
            for char in self.sequence:
                composition[char] = composition.get(char, 0) + 1
            return composition

        def find_motif(self, motif):
            """Finds the motif in the sequence and returns its positions."""
            matches = re.finditer(motif, self.sequence)
            return list(matches)
    return (Sequence,)


@app.cell
def _(Sequence):
    seq = Sequence("AcGTaCGtAgA")
    return (seq,)


@app.cell
def _(seq):
    seq.sequence
    return


@app.cell
def _(seq):
    seq.get_length()
    return


@app.cell
def _(seq):
    seq.get_composition()
    return


@app.cell
def _(seq):
    seq.find_motif("AC")
    return


@app.cell
def _(Sequence):
    class DNA(Sequence):
        def __init__(self, sequence):
            super().__init__(sequence)
        
            if set(self.sequence) != set("ATGC"):
                raise ValueError("DNA sequence can only contain A, T, C, and G.")

        def get_orf(self):
            seq = self.sequence
            seqlen = self.get_length()
    
            start_codons = ["ATG", "GTG"]
            stop_codons = ["TAG", "TAA", "TGA"]
    
            for frame in [0, 1, 2] :
                i = frame
    
                for i in range(frame, seqlen-2, 3) :
                    start_codon = seq[i:i+3]
    
                    if start_codon in start_codons :
    
                        for j in range(i, seqlen-1, 3) :
                            stop_codon = seq[j:j+3]
    
                            if stop_codon in stop_codons :
                                orf = seq[i:j+3+1]
                                print(f"ORF found in frame {frame+1} from {i+1} to {j+3}:")
                                print(orf)
                                i = j
                                break
    return (DNA,)


@app.cell
def _(DNA):
    dna = DNA("CCAGTTATCGAAAAAAAGTGAAGCGTAAAAACTAAACGGTACTTGGAAAATTTACTTTGCCTGTGTGCGTGCTTCTGTTTATGAAAACTACGTTTTTAAGCATTTGCAATTGATGCAACGTTGCTTTGGAAGGCAAGAAAACACCAAGTGGAAACGCCCGGGTGGCGGAAATCGACTTCCAGTGCGCGAGTGCGAGATTGTGTGTGTTTCGTTCCGTCCTCTGGTGTCTGGCACCTTAACACAACAACAACTACAGCAGCAGCAGCAACAACAACAATAGCAAGCAGCAACAACAACACACGCACAATAATAAGAAGGCCTGTGACGTTGTCGCTGCCGTCACCATCTAAAGGAAAATACCAAAACGAGTAGGAAAACAAACCGCAGTGCAGTAGGGAAAGCAAAAGTCGGGTTTTTTTTTTTACAAAACTAGGTCCCTCATTAGCTTGTCCCTAGGGTTAGTGAAACAGCCTCAACACGAATTACCTACCGTTTGTTCTTCAGCGGCGATCGACTGTGGTTGCCAGCGCCCCAGCGCCAGGATCTGCCTCTAGGATCCCGGAATCGCCCACCACCACAGGGAGCAACATCATTAACATCATCTACAGCCAATCCACCCATCCAAACAGCAGCCCCACCAGCGGCAGTGCAGAGAAATTCAGCTGGCAGCAATCCTGGCCAAGCAGGACCTCCGCGGCCCCTACACACGATTCCGGAACCATGTCAATAAACACAACTTTCGACCTCAGCTCGCCCAGCGTTACATCGGGTCATGCGCTTACGGAACAGACTCAGGTCGTAAAGGAGGGGTGGCTGATGAAGAGGGGCGAGCACATAAAGAACTGGCGCCAGCGCTACTTCGTGCTCCACTCCGATGGAAGACTGATGGGTTACCGCAGCAAGCCGGCAGATAGTGCCAGCACGCCATCGGACTTCCTGCTCAACAACTTTACGGTGCGCGGCTGCCAGATCATGACCGTCGATCGGCCCAAGCCATTCACCTTCATCATCCGCGGCCTGCAATGGACCACGGTAATCGAAAGGACATTTGCCGTCGAATCAGAATTAGAGCGCCAGCAGTGGACGGAGGCCATTCGCAACGTATCCAGCCGGCTCATAGATGTGGGTGAGGTGGCTATGACGCCATCTGAACAGACAGACATGACAGACGTGGACATGGCCACCATTGCCGAGGACGAGCTTTCCGAGCAGTTCTCCGTACAGGGAACGACTTGTAATAGCAGCGGCGTTAAGAAAGTGACTTTGGAGAATTTTGAGTTCCTCAAGGTGCTCGGCAAGGGCACCTTTGGTAAGGTTATTTTGTGTCGCGAGAAGGCTACCGCCAAGCTGTACGCGATCAAAATTCTTAAAAAGGAAGTTATTATCCAAAAGGACGAGGTGGCCCATACCCTGACCGAGAGTCGTGTGCTCAAGTCCACAAATCATCCGTTCCTCATTTCACTCAAATATTCGTTTCAAACCAACGACCGCCTGTGTTTTGTGATGCAGTACGTGAACGGTGGCGAGCTCTTTTGGCATTTAAGCCACGAACGCATATTTACTGAGGATCGAACACGTTTCTATGGGGCAGAGATCATTTCTGCTCTGGGCTATCTGCATTCACAGGGCATAATTTATCGCGACTTAAAGCTGGAAAATCTTTTGCTGGACAAAGATGGTCACATAAAGGTCGCAGACTTCGGTCTGTGCAAGGAGGACATCACCTACGGCCGCACAACGAAAACCTTCTGCGGTACACCGGAATACCTAGCTCCGGAAGTATTAGATGACAATGATTATGGCCAAGCGGTGGACTGGTGGGGCACTGGCGTGGTCATGTACGAGATGATCTGTGGTCGTCTTCCGTTTTACAATCGTGATCATGATGTGCTCTTTACATTGATTTTGGTGGAGGAGGTAAAATTCCCGCGTAATATCACAGATGAGGCGAAAAATCTGTTAGCAGGCCTTCTAGCTAAGGATCCCAAAAAGCGTTTGGGAGGTGGAAAGGATGATGTCAAGGAGATACAAGCACATCCATTCTTTGCGAGTATTAACTGGACAGATCTAGTGTTGAAAAAAATACCGCCGCCTTTCAAGCCTCAGGTGACATCCGATACGGATACAAGGTACTTCGACAAGGAGTTTACGGGAGAGAGTGTGGAGTTGACGCCGCCGGATCCCACTGGCCCGTTGGGCTCCATAGCCGAAGAGCCGCTTTTCCCGCAGTTCAGCTACCAAGGAGACATGGCCTCCACGTTGGGCACCTCGTCGCACATTAGTACTTCCACAAGTCTCGCATCGATGCAATAGAACAAGTTTACAAACTTTTACCAGCACACATCATGTTCTGCTTCATCACCTATTACTATACTATACCTATAACACATAGAAATGGGCAAAAGAAAACAACAGCAAGAATATATTAAATATTAATTATACCATGATAACGAAGGCAAGCAAAGGGTTTTCTTGCTAGTTTATATACACCAATAATAAGAGAATTGAATTGATAGTAACTTATTTTTGTATAATGAGAAAGGGAACGTTGAACGAAAGGGCAACAGCCGAAGCCGAGGAAAATAATTTACTACATATGATTATACACATATATATAAATATATATATATATATATATATAATTATATATACAACTAAATATAACACTTGGGGCATAGCGCTTGAAGTGATTAGTTAATTTTAAACGCAAGGAAAACATTTAACCAAGCGACTTAGAGCGACTTAGTGCTAGGATAAAGCATGCATCATCGGATCGCATCCTCTAGGGGTCGCTTAAGCTGATTGATTATACAGATTATTCACGCAGACAGCACTCACACAGCCACTTAGCATATAGCGAACATGAAGTTTAGTTAACTTGACAGCAACAAATCGAAATACACATATTCAACAACCGCCCCCACATGCAACACTCGTATATATAAATTATTTATACTCCAAAGAAGCAAAAAAGAAACAGAAACAATTACAAGTTATATATAATGTTAAAATTGCCTCTAATGTGCTGTGCTTTATGCAAAACTACAACAACAGAAACAAACAAACTAATAGTTAATAAACGAGGGAAACATACATCAATGCAGTTTATAGGCGCCAATAATTAGCAAGCAACTAAAAGTTATATTCAGGCAGAAACATATTTCGAAACAATAACGGCAACAGCAAAATGATTACAATTGACGCCATTTTTTATTATAATTTTTTACGAAAAATATATATTTGTAAATATTTATAAAAAAAAAGCAAAAACTCAAGAGTAAATGCAAAAAAAAAACAAAGGATGTATGTGTCGTGTGGAAAATGGAAGTCACCATTTGAGGCCACAGAAAAGGTTTAACCTTTGACACAATAAAAAATGTATCTTTGTCATTTCATTTTTGGCATTGAAAAGTTCATAACAAGTTTTGTATACTTAGAGCAAGTCAGCAAAAAATATATATAAATCAACCACAACAGACTTACAAATAGTTCCAAAAGGAAGATTAAAAATTATATAAACAGAAAAAAAACCTAAAAGAAAATAAAGAATTTTTGATATTTTTATATGCGCAATAAAAACAAAAATCAAGAATAAAACGAAACAAAAAGTTATTTTATATTTCGTAAAGAAAACAAAATAAATATTGTAAATAAAAATTATTAAATAAAATCAAGTTCGGGAATTTCAACTGAAAACAAAGAAATTGAAAGCATAATCTCTCTTCTAAATGTTAAACGAAACCTATCACTCGATGATTACAATAAACAGCAAATCGAAAACGAAGGGATATAGAAACGAAAAGAAAATGCCAAAGAAGCGGCGAAGTTAGGTGGAACTCGAGGAGAACCGAGAATTGAGGAGCCAGCAAGTCGGGATGTTTCGGTTGGAGTCTTGGACATGTGACGATGATGGTTCCAAATCATGACTAGGAACGAACTAACTAGCTAAAGCCAGCCTATGCTGAGGAGAGATATCAGATAGCTCCGATTGAACCAATCTTTATATCCTTGAACAGCTTAAAGTCCTTGCTTTCTGCTCACCAAGTTTGCGGCTGACATCTAGGCTAGCCAATATCAATCTCAGATCGATCAAGCAATACATAGACAAAATATAGAACCCCTAAGCATGGCTTAATAGACATACAACCCGAGAATCGACTTCAACAAGCCCAATAACCCTTCTGACAGACTCGTTAGGCAAGTCTGCCAGCCAAGGGGCAACCAGCTAGAAATCTAAAGCAAAGACTTAGAAATCGGTTAGGGACATCCGAAGCAAATTGAATACTAGCCTTAGTGAACGTCAACATCTCTGGTATCCCAAATCGAAGCATTTTCTACCCGTCGAAGGGGACGAAAGAGACCTTTCAAAATAGTTGTCTAAGTTTACTGAGTTGTGTGAGACAATTTTTGGTTTCGATTAAAAAAAAAAAAACAAAAACTTACACGAACTGCAAACTACAATGTGTTCTAAAGCGATATAATAAAACAACATGGTTTAAAATTGACTATATATAGAAAGAAACCGAGAGAGATATAACCAGTCAGATCATAGATCATCTCGAGCAACTTGAGTTGTTTTTTGTATTGTAAAATAGAAAAAGATAAACCCGTTCCAACAACCGAGATCCAGATCCAGATCCAGCCCCCAATACTAACCGAAAATTTGATTAGGAGTAATTTTTGATAGGCGAAAATGCGAGTTTCGCACAGTTTTAATTATTAATTATATTAAATAAAGATAATAATGACTAAGCTGATTTATAAAACGATTCAAGATCGAACTAAAACATACATATACATGCATTCAAACCAAGTTTATTATACAGTGAAAACATAATAATAAAACTACATAAAACCAAACTACTATGC")
    return (dna,)


@app.cell
def _(dna):
    dna.get_length()
    return


@app.cell
def _(dna):
    dna.get_composition()
    return


@app.cell
def _(dna):
    dna.get_orf()
    return


@app.cell
def _(Sequence):
    class Protein(Sequence):
        def __init__(self, sequence):
            super().__init__(sequence)
    return (Protein,)


@app.cell
def _(Protein):
    protein = Protein("ALMMKLKCALKCHLAMAGMLKLGKMGHCHHMLMAHGMLHLMHGGHHGAKHCCAACALHMGGGKGHHMGGKALMMLMLKALCMCMKGMGCKMGKHAKKHCK")
    return (protein,)


@app.cell
def _(protein):
    protein.get_length()
    return


@app.cell
def _(protein):
    protein.get_composition()
    return


if __name__ == "__main__":
    app.run()
